VillaProject_WEB/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using VillaProject_Utility;
using VillaProject_WEB.Models;
using VillaProject_WEB.Models.DTO;
using VillaProject_WEB.Services.IServices;

namespace VillaProject_WEB.Controllers
{
	public class AuthController : Controller
	{
		private readonly IAuthService _authService;
		public AuthController(IAuthService authService)
		{
			_authService = authService;
		}

		[HttpGet]
		public IActionResult Login()
		{
			LoginRequestDTO loginRequestDTO = new();
			return View(loginRequestDTO);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Login(LoginRequestDTO loginRequestDTO)
		{
			var response = await _authService.LoginAsync<APIResponse>(loginRequestDTO);
			if(response != null && response.IsSuccess)
			{
				LoginResponseDTO model = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result));

				var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
				identity.AddClaim(new Claim(ClaimTypes.Name, model.User.UserName));
				identity.AddClaim(new Claim(ClaimTypes.Role, model.User.Role));
				var principal = new ClaimsPrincipal(identity);
				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

				HttpContext.Session.SetString(SD.SessionToken,model.Token);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ModelState.AddModelError("Error", response.ErrorMessages.FirstOrDefault());
				return View(loginRequestDTO);
			}
		}

		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Register(RegistrationRequestDTO registrationRequestDTO)
		{
			var result = await _authService.RegisterAsync<APIResponse>(registrationRequestDTO);
			if (result != null && result.IsSuccess)
			{
				return RedirectToAction("Login");
			}
			return View();
		}

		[HttpGet]
		public async Task<IActionResult> Logout()
		{
			HttpContext.SignOutAsync();
			HttpContext.Session.SetString(SD.SessionToken, "");
			return RedirectToAction("Index", "Home");
		}

		[HttpGet]
		public async Task<IActionResult> AccessDenied()
		{
			return View();
		}
	}
}

VillaProject_WEB/Controllers/VillaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VillaProject_Utility;
using VillaProject_WEB.Models;
using VillaProject_WEB.Models.DTO;
using VillaProject_WEB.Services.IServices;

namespace VillaProject_WEB.Controllers
{
	public class VillaController : Controller
	{
		private readonly IVillaService _villaService;
		private readonly IMapper _mapper;
		public VillaController(IVillaService villaService, IMapper mapper)
		{
			_mapper = mapper;
			_villaService = villaService;
		}
		public async Task<IActionResult> IndexVilla()
		{
			List<VillaDTO> list = new();

			var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
			}
			return View(list);
		}

		[Authorize(Roles ="admin")]
		public async Task<IActionResult> CreateVilla()
		{
			return View();
		}
		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
		{
			if (ModelState.IsValid)
			{
				var response = await _villaService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Number created successfully";
					return RedirectToAction(nameof(IndexVilla));
				}
			}
			TempData["error"] = "Error encountered";
			return View(model);
		}

		[Authorize(Roles = "admin")]
		public async Task<IActionResult> UpdateVilla(int villaId)
		{
			var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				var dto = Convert.ToString(response.Result);
				VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(dto);
				return View(_mapper.Map<VillaUpdateDTO>(model));
			}
			return NotFound();
		}

		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
		{

			if (ModelState.IsValid)
			{
				var response = await _villaService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Number created successfully";
					return RedirectToAction(nameof(IndexVilla));
				}
			}
			TempData["error"] = "Error encountered";
			return View(model);
		}

		[Authorize(Roles = "admin")]
		public async Task<IActionResult> DeleteVilla(int villaId)
		{
			var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				var dto = Convert.ToString(response.Result);
				VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(dto);
				return View(model);
			}
			return NotFound();
		}
		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteVilla(VillaDTO model)
		{

			var response = await _villaService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				TempData["success"] = "Number created successfully";
				return RedirectToAction(nameof(IndexVilla));
			}
			TempData["error"] = "Error encountered";
			return View(model);
		}
	}
}

VillaProject_WEB/Controllers/VillaNumberController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using VillaProject_Utility;
using VillaProject_WEB.Models;
using VillaProject_WEB.Models.DTO;
using VillaProject_WEB.Models.VM;
using VillaProject_WEB.Models.VM.Interface;
using VillaProject_WEB.Services.IServices;

namespace VillaProject_WEB.Controllers
{
	public class VillaNumberController : Controller
	{
		private readonly IVillaNumberService _numberService;
		private readonly IVillaService _villaService;
		private readonly IMapper _mapper;

		public VillaNumberController(IVillaNumberService numberService, IVillaService villaService, IMapper mapper)
		{
			_numberService = numberService;
			_villaService = villaService;
			_mapper = mapper;
		}

		public async Task<IActionResult> IndexVillaNumber()
		{
			List<VillaNumberDTO> list = new();

			var response = await _numberService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				var result = Convert.ToString(response.Result);
				list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(result);
			}
			return View(list);
		}

		[Authorize(Roles = "admin")]
		public async Task<IActionResult> CreateVillaNumber()
		{
			VillaNumberCreateVM villaNumberVM = new(await GetVillaNumberVM());

			return View(villaNumberVM);
		}
		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
		{
			if (ModelState.IsValid)
			{
				var response = await _numberService.CreateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Number created successfully";
					return RedirectToAction(nameof(IndexVillaNumber));
				}
				else
				{
					if (response.ErrorMessages.Count > 0)
					{
						ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
					}
				}
			}
			TempData["error"] = "Error encountered";
			model.VillaList = await GetVillaNumberVM();
			return View(model);
		}

		[Authorize(Roles = "admin")]
		public async Task<IActionResult> UpdateVillaNumber(int villaNo)
		{
 
			VillaNumberUpdateVM villaNumberUpdateVM = new(await GetVillaNumberVM());
			var response = await _numberService.GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				var dto = Convert.ToString(response.Result);

				villaNumberUpdateVM.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(JsonConvert.DeserializeObject<VillaNumberDTO>(dto));
				return View(villaNumberUpdateVM);
			}
			return NotFound();
		}

		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
		{

			if (ModelState.IsValid)
			{
				var response = await _numberService.UpdateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(SD.SessionToken));

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Number updated successfully";
					return RedirectToAction(nameof(IndexVillaNumber));
				}
			}
			TempData["error"] = "Error encountered";
			return View(model);
		}

		[Authorize(Roles = "admin")]
		public async Task<IActionResult> DeleteVillaNumber(int villaNo)
		{
			var response = await _numberService.GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				var dto = Convert.ToString(response.Result);
				VillaNumberDeleteDTO model = JsonConvert.DeserializeObject<VillaNumberDeleteDTO>(dto);
				return View(model);
			}
			return NotFound();
		}
		[Authorize(Roles = "admin")]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteDTO model)
		{

			var response = await _numberService.DeleteAsync<APIResponse>(model.VillaNo, HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				TempData["success"] = "Number deleted successfully";
				return RedirectToAction(nameof(IndexVillaNumber));
			}
			TempData["error"] = "Error encountered";
			return View(model);
		}

		private async Task<IEnumerable<SelectListItem>> GetVillaNumberVM()
		{
			var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));

			if (response != null && response.IsSuccess)
			{
				var villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(
					Convert.ToString(response.Result))
					.Select(i => new SelectListItem
					{
						Text = i.Name,
						Value = i.Id.ToString()
					});
				return villaList;
			}
			return Enumerable.Empty<SelectListItem>();
		}
	}
}

VillaProject_WEB/Views/Shared/_Layout.cshtml
@using VillaProject_Utility
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAccessor;

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - VillaProject_WEB</title>
	<link rel="stylesheet" href="~/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/VillaProject_WEB.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
	<partial name="_Notification"></partial>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark  box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VillaProject_WEB</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Numbers</a>
						</li>
						@if (httpAccessor.HttpContext.Session.GetString(SD.SessionToken) != null &&
											httpAccessor.HttpContext.Session.GetString(SD.SessionToken).ToString().Length > 0)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">LogOut</a>
							</li>
						}
						else{
						<li class="nav-item">
							<a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
						</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="footer text-muted">
		<div class="container">
			&copy; 2024 - VillaProject_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VillaProject_WEB/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"] != null)
{
	<script type="text/javascript">
		Swal.fire({
			position: "top-end",
			icon: "success",
			title: '@TempData["success"]',
			showConfirmButton: false,
			timer: 2000,
			timerProgressBar: true,
			background: '#343a40', 
			confirmButtonColor: '#28a745', 
			theme: 'dark' 
		});</script>
}
@if (TempData["error"] != null)
{
	<script type="text/javascript">
		Swal.fire({
			position: "top-end",
			icon: "success",
			title: '@TempData["error"]',
			showConfirmButton: false,
			timer: 2000,
			timerProgressBar: true,
			background: '#343a40', 
			confirmButtonColor: '#28a745',
			theme: 'dark' 
		});</script>
}